### ISSUE TITLE
【Feature】dubbo3服务柔性与限流实现方案

### ISSUE THREAD

**Issue by kaori-seasons** [complone/dubbo#2]
# 架构
## 现有架构
Cluster 是指一个 invoker 集群，向外暴露一个 ClusterInvoker 实例，在 Invoke 方法被调用时，通过一个 LB 算法选择一个 invoker 进行调用。所以，当前版本 Cluster 是接口级的，同样的，原有的 LB 也是接口级的。
LoadBalance 最细粒度是方法级，LoadBalance 的信息放在 DubboURL 中，首先读取的是服务级的 LB，如果没有则设置为 `ramdom`，然后读取方法级 LB，如果有存在则覆盖服务级 LB。
场景1：如果一个 iface 下的 method1 和 method2，method1 使用的是 random，method2 使用的是 FS，那么服务端返回 method1 结果时不需要采集数据，返回 method2 时需要采集。Dubbo 协议可以通过 attachment 特性实现的，triple 协议待定。
## 架构改进
在 cluster 包下引入 Metrics，用于记录与柔性服务相关的指标。在早期版本中，只实现 local 模式，后续可以实现 remote、p2p 等模式，因为服务器的数据是可以与周围邻居共享的。

- Filter or Non-Filter: 
![image](https://github.com/kaori-seasons/dubbo/assets/20021404/98e668c1-2c0f-49c8-bc25-c58bbc87ed86)

上图展示了柔性服务的总体框架，主要参与的模块是 FS cluster invoker、P2C loadbalance、FS filter、LocalMetrics 和 CapacityEvaluator。
### Metrics(client)
LocalMetrics 是指一个本地模式使用一个 Map 保存数据，用户可以自由添加 KV 数据以满足 LB select 结点的要求。
由于 Map 的灵活性，可以保证 Instance 级的 Metrics 和 Invoker 级的数据都能存放在一个 Map 下，这里只需要对命名进行规范即可：

- Instance 级的，命名方式为 "ins.{Metrics Name}"，比如 CPU Load 等指标
- Invoker 级的，命名方式为 "ivk.{Invoker Name}.{Metrics Name}"，比如请求成功率等
- Method 级别，命名方式为 "mtd.{Invoker Name}.{Method Name}.{Metrics Name}"，比如 Vegas 容量评估等

问题 1：Map 必须保证 thread-safe，在频繁调用的时候，Map 的写入量可能会比较大，会不会有潜在的性能瓶颈？
解决办法 1：采用多级 Map 结构的方式，最顶层采用 InstanceMetrics，InstanceMetrics 中包含 InvokerMetrics，最后保护 MethodMetrics。
Metrics 记录的是服务器的数据，那么为什么不直接用 ServerMetrics 呢？这里主要考虑的是一个服务器中可以部署多个 dubbo-go instance（实例），而各个实例可能通过 cgroups 等方式设置不同的资源，所以这里以 Dubbo 实例为观测单位。
在 local 模式下，一个 dubbo 实例内共用一个 map（thread-safe），map 的 key 表示的是一个应用级实例的 dubbo 实例，格式为 "{ipaddr}:{port}"，value 是一个 Metrics 实例，可以用于记录服务端的数据。
为什么使用 IP + 端口的方式？只要是同一个端口我们可以认为属于同一个实例，他们的 Metrics 是可以共用的，这样可以避免每个 invoker 都自己维护服务器状态。
### FS Cluster Invoker
FS cluster invoker（FSCI）是 FS 的核心组件，从架构图中也能看到整个流程都是基于 FSCI 展开的。
FSCI 主要的功能是：

- 维护 Invoker 列表（Directory）
- LoadBalance 选择器（目前仅可以使用 P2C）
- 维护 Metrics，集成在 FSCI 中可以少用一个 Consumer 端 Filter 【新增】

另外一个新增功能就是维护 Metrics，根据回传数据进行更新 Metrics。
### LoadBalance
LB 的作用是根据传入的状态选择一个合适的 Invoker，所以认为 LB 的作用是选择节点，所以它不维护节点的状态信息。

![image](https://github.com/kaori-seasons/dubbo/assets/20021404/43c06f72-ceff-4cfa-84fc-eb598c272006)

P2C loadbalance 能够从一个 invoker 列表中通过 P2C 算法选择一个 invoker，在 Java 现行的方案中，不是传统意义上的 P2C 算法，因为后端的选择不在是 CPU Load 等，而变成了 Vegas 容量评估算法，Vegas 算法在理论上应该是改进了 P2C 采集数据维度不足的问题。
### CapacityEvaluator(server)
讨论 1：在 Java 中，容量评估使用的是 Limit + Limiter 的实现，但是我觉得 Java 在命名时会让人产生困惑，这个地方的初衷是用来评估服务端容量的，而非做限流的，所以这个命名方式还有待讨论。
讨论 2：在 Java 中（[https://github.com/apache/dubbo/pull/8967/files#r731502394](https://github.com/apache/dubbo/pull/8967/files#r731502394)），使用一个静态变量存储 method -> limiter 的映射关系，但是没有考虑到命名空间的问题，正如我留言的一样可能会导致命名冲突，这个地方也需要进一步讨论。
在 provider 端做容量评估，应该**只需要**评估方法级的容量，且当前数据不需要与其他结点分享，所以 provider 端保存 Metrics 数据的方案相对更容易些。基本结构上需要与 Metrics 对齐，也就是通过分级结构作为方法名的 namespace。
# 算法细节
## P2C 算法
问题 1：考虑统计哪些指标作为最终的负载率的计算？
问题 2：如果server节点少的话，基本上达不到按照权重分配请求数量，权重小的那个节点是永远不会被选中的， 可以通过加 idle time 到一定时间强制选中来处理，即使这样权重小的那个节点还是会少很多请求打过去。
问题 3：ewma里的那个半衰函数（tau）的值很重要，ms、s 单位会影响计算的准确性
问题 4：幂等情况下的重试机制，注意异步调试如何重试
问题 5：调用端超时中断。超市时间如何评估？第一次请求延迟时间？第一次请求但是还没有任何返回的时候，超时时间？

![image](https://github.com/kaori-seasons/dubbo/assets/20021404/c886fa6e-d75e-4bd2-8329-9e83df50de78)

P2C 在实现上比较简单，首先需要随机 select 两个结点，然后比较两个结点的服务器容量，在最初版本中，Vegas 算法作为服务器容量评估的实现。
## Vegas 算法
问题 1：egas想法感觉很好，但是效果感觉一般，感觉要找一个合适的模型去拟合服务端性能，如果拟合效果差的话，可能还不如直接采集一些硬件数据，CPU使用率，内存使用率，rtt这些。
问题 2：评估算法
问题 3：线程/协程的饱和度（TPS 限流）、fast-fail（执行时间长直接打断）
问题 4：根据服务端容量调整 client 的 weight
问题 5：Vegas 算法是采用方法级采样，还是接口级采样。
问题 6：在 Java 中 VegasLimiter 除了容量评估外，还有流控的作用，是否与 TPSLimiter 的功能重复

# 配置文件
配置文件根据 consumer 和 provider 分为两种配置，consumer 负责指定方法是否使用 FS，默认不使用 FS。因为 FS 和 LB 在部分情况下重合，这里把所有可能的情况列出。
默认不启动 FS
```yaml
dubbo:
	consumer:
  	registry: zk
    references:
    	GreeterImpl:
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
```
显式规定不启动 FS
```yaml
dubbo:
	consumer:
  	adaptiveService: false
  	registry: zk
    references:
    	GreeterImpl:
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
```
所有 references 启动 FS
```yaml
dubbo:
	consumer:
  	adaptiveService: true
    registry: zk
    references:
    	GreeterImpl:
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
```
~~除了指定 reference 开启 FS，其他 references 都不开启 FS~~
```yaml
dubbo:
  consumer:
    registry: zk
    references:
      GreeterClientImpl:
        flexibleService:
          method: p2c
          mode: local
        protocol: tri
        interface: com.apache.dubbo.sample.basic.IGreeter
      GreeterClientImpl1:
        protocol: tri
        interface: com.apache.dubbo.sample.basic.IGreeter1
```
~~除了指定 reference 不开启 FS，其他 references 都开启 FS~~
```yaml
dubbo:
  consumer:
    flexibleService:
    	method: p2c
    	mode: local
    registry: zk
    references:
      GreeterClientImpl:
        flexibleService:
    			method: none
        protocol: tri
        interface: com.apache.dubbo.sample.basic.IGreeter
      GreeterClientImpl1:
        protocol: tri
        interface: com.apache.dubbo.sample.basic.IGreeter1
```
~~FS 优先级 > LoadBalance 优先级~~
```yaml
dubbo:
	consumer:
  	flexibleService:
    	method: p2c
      mode: local
    registry: zk
    references:
    	GreeterImpl:
      	loadbalance: random					# loadbalance 不生效，因为 FS 优先级更大
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
      
dubbo:
	consumer:
  	flexibleService:
    	method: p2c
      mode: local
    registry: zk
    references:
    	GreeterImpl:
      	flexibleService:
          method: none
      	loadbalance: random					# loadbalance 生效，因为 GreeterImpl 的 FS 被禁用了
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
        
dubbo:
	consumer:
    registry: zk
    references:
    	GreeterImpl:
      	flexibleService:
          method: p2c
      		mode: local
      	loadbalance: random					# loadbalance 不生效
    		protocol: tri
      	interface: com.apache.dubbo.sample.basic.IGreeter
```
Provider 端也需要配置静态权重，权重范围暂定 uint32（0-2^32)，越大表明服务器的配置越高（后续，可以根据 CPU、内存等状态自动评估静态权重），只要使用了 flexiableServiceWeight 就表明开启 FS。
```yaml
dubbo:
	provider:
  	flexibleServiceWeight: 100
```
两边都要设置 FS 才能启用，这里讨论下两种不同的异常场景：

1. Consumer 开启了 FS，provider 未开启（包括部分 provider 未开启情况）：attachement 的数据不合法，不会更新数据收集，需要标记 provider 端 FS 不可用，这样下次调用其他指标都会暂停采集。
2. Consumer 未开启 FS，provider 开启：attachment 缺少对应的 key，provider 的 filter 将不会采集 CPU 等信息。
# 指标收集 [暂时不用]
P2C 关系的指标有 3 类，分别是：

- 静态权重：由用户在配置文件中自行指定
- 服务器数据采集：利用 dubbo attachement 机制传递服务器指标
- 客户端数据采集：利用 filter 机制采集

接下来将详细介绍服务器和客户端数据采集的步骤。
服务器状态共享，比如 iface1 和 iface2（服务对服务）、iface1 和 method1（服务对方法）以及 method1 和 method2（方法对方法）都是由 server1 提供，那么应该可以让他们之间共享服务器状态。因此服务器状态信息不能由 invoker 持有，必须由 cluster 或更高级别持有。
## 服务端信息 [暂时不用]
Consumer 开启了 FS 后，将通过 `Filter::Invoke` 方法为 attachement 携带一个 `"FlexibleService": "cpu,memory"` 的键值对，表示需要服务端返回 cpu 和 内存状态。（后续可以考虑采用二进制的方式传递数据，但在第一版中考虑到可读性，先采用字符串的方式）
Provider 的 Filter 在 OnResponse 中根据这个 attachment 中的数据获取对应的资源状态后，再复用 `FlexibleService` Key 返回相应的数据，比如 `29.00,40.00`，表明 CPU 占用率 29%，内存占用率 40%。
Consumer 在 Filter 的 OnResponse 携带的 attachment 数据保存到 invoker 中，为了不侵入 baseInvoker，设计一个 FlexibleInvoker 接口，
